type Query {
  books: [Book!]!
}

type Mutation {
  uploadBook(data: UploadFileInput!): Book!
}

input UploadFileInput {
  file: Upload!
  bookCreateInput: BookCreateInput!
}

input BookCreateInput {
  title: String!
  isbn: String
}

type Book {
  id: Int!
  title: String!
  isbn: String
  url: String
}

scalar Upload
